### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by adamlytics** [pratik227/quasar-qgrid#1]
This extension looks awesome, but I cannot get it to install.  The `quasar ext add qgrid` command seems to work, but when trying to use the extension, it doesn't identify it and none of the code examples work.  I understand that it is a WIP, should it be working?

**Comment by pratik227** [comment]
It should work. if you can provide some extra details or repo on github will be great.

**Comment by pratik227** [comment]
Closing this because of no reply
