### ISSUE TITLE
dragged_row not declared in emits or props

### ISSUE THREAD

**Issue by bdelate** [pratik227/quasar-qgrid#113]
Hi,

When running the following example:
https://stackblitz.com/edit/quasarframework-ujyqyf?file=src%2FApp.vue

The console displays the following warning when dragging a row:
`[Vue warn]: Component emitted event "dragged_row" but it is neither declared in the emits option nor as an "onDragged_row" prop.`

I presume you need to define `dragged_row` as an emit within `QGrid.vue`?

**Comment by pratik227** [comment]
Hi @bdelate,

My bad.  think it's removed in some commits I don't remember where sorry!!. Just published the new version.

Thanks,
Pratik Patel

**Comment by bdelate** [comment]
Great, thank you @pratik227
