### ISSUE TITLE
QGrid Date Range Filter

### ISSUE THREAD

**Issue by dhakenlan2112** [pratik227/quasar-qgrid#128]
There's issue when filter the same date, it will show undefined. 
how to fix this?

**Comment by pratik227** [comment]
Please provide some sample code

**Comment by dhakenlan2112** [comment]
The code is as like the doc
 <q-grid
      id="table-storage"
      :data="rows"
      :columns="columns"
      row-key="name"
      separator="cell"
      class="text-align-center grid-table page-wrapper q-mb-sm"
      :rows-per-page-options="[0]"
      :pagination="pagination"
      :no-data-label="$t('noData')"
      :hide-bottom="Object.keys(rows).length > 0"
      :columns_filter="true"
      >
</q-grid

and the columns,
columns: [
        ...
        {
          name: "expired_date",
          label: "Expiry",
          align: "center",
          field: "expired_date",
          headerClasses: "bg-accent text-primary",
          filter_type: "date"
        },
       ...
],
this columns using filter type date, and the type of filter is date range right? 
the issue is when we filter 1 date (ex. 15 June - 15 June) it will show undefined:
![filterdate](https://github.com/pratik227/quasar-qgrid/assets/54022755/30d99859-df86-40e2-98e8-2c7cb2566cdb)

**Comment by dhakenlan2112** [comment]
any updates?

**Comment by pratik227** [comment]
Hi,


Sorry actually it's festival season is going on I'm on vacation i will take a look once i get back.

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
https://github.com/pratik227/quasar-qgrid/pull/140

It's available in new version.
