### ISSUE TITLE
Vue-3 issues

### ISSUE THREAD

**Issue by MobideoNetser** [pratik227/quasar-qgrid#13]
Hello. very nice work.
There are some issues with vue3 and using some deprecated functions.
 I attach it hereL 
 23:28  error    '.native' modifier on 'v-on' directive is deprecated

                       vue/no-deprecated-v-on-native-modifier
  152:21  error    `slot` attributes are deprecated

                       vue/no-deprecated-slot-attribute
  152:35  error    `slot-scope` are deprecated

                       vue/no-deprecated-slot-scope-attribute
  154:39  error    The 'props.cols' expression inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
  159:25  error    `slot` attributes are deprecated

                       vue/no-deprecated-slot-attribute
  159:37  error    `slot-scope` are deprecated

                       vue/no-deprecated-slot-scope-attribute
  161:41  error    The 'props.cols' expression inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
  334:17  error    Unexpected side effect in "getFilteredValuesData" computed property
                       vue/no-side-effects-in-computed-properties
  357:21  error    Unexpected side effect in "getFilteredValuesData" computed property
                       vue/no-side-effects-in-computed-properties
  363:29  error    The `$scopedSlots` is deprecated

                       vue/no-deprecated-dollar-scopedslots-api
  363:42  error    Do not access Object.prototype method 'hasOwnProperty' from target object
                       no-prototype-builtins
  399:26  error    Do not access Object.prototype method 'hasOwnProperty' from target object
                       no-prototype-builtins
Regards

**Comment by pratik227** [comment]
Hi @MobideoNetser ,

It's not migrated yet with Vue 3. I will migrate this extension soon.

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Just Released the first version. Try 1.0.0-alpha.1 version.

https://next-quasar-qgrid.netlify.app/

**Comment by MobideoNetser** [comment]
Thanks
