### ISSUE TITLE
loading prop

### ISSUE THREAD

**Issue by TribesTom** [pratik227/quasar-qgrid#14]
Hello,

Thank you for your plugin. It's very complete.

I have a question :
Is there a way to use the loading prop like quasar table ?

Br,

**Comment by pratik227** [comment]
Hi @TribesTom, I have not added loading props in the QGrid. I will add in the new version for sure.

Thanks,
Pratik Patel

**Comment by TribesTom** [comment]
Hello,

Thanks for your response.

**Comment by pratik227** [comment]
Hi @TribesTom,

I have deployed the changes plz try the latest version.

Thanks,
Pratik Patel
