### ISSUE TITLE
Select column filter not updating with new data

### ISSUE THREAD

**Issue by TribesTom** [pratik227/quasar-qgrid#16]
Hello,

It's seems the column select filter values are not updating when the data change.

I pull the data from a backend so it's not know at the load time and It can change depending of the search.

To resolv this, I have created a method which refresh this.

`          getColumnOptions(column) {
              let column_option_simple = [...new Set(this.data.map(item => item[column]))];

              let column_option = []

              for ( let col of column_option_simple) {
                  column_option.push({'label' : col.toString(), 'value': col.toString().toLowerCase().replace(/_/g, '_')})
              }

              return column_option
            }`

And I call it in the template : 

`              <q-select v-if="col.hasOwnProperty('filter_type') && col.filter_type=='select'" map-options
                        multiple emit-value filled v-model="column_options_selected[col.field]"
                        :options="getColumnOptions(col.field)" dense>`

I don't know if it's the best way but It seem's to run good

**Comment by pratik227** [comment]
Hi @TribesTom,

Ok, I will add this logic in the next release.

**Comment by pratik227** [comment]
Hi @TribesTom,

I have deployed the changes plz try the latest version.

Thanks,
Pratik Patel
