### ISSUE TITLE
QGrid issues with filter and grouping

### ISSUE THREAD

**Issue by fandegoldo** [pratik227/quasar-qgrid#17]
Hi,

First, thanks for your work on QGrid extension, it is very appreciate.

There are severals issues detected when i have tested:
- grouping don't work when you want to customize slots
- header filter don't work when you want to customize slots
- filter with selected options don't work when you want to customize slots (for example, i have replaced value true/false by a checkbox)

Thanks in advance.

Best regards.

**Comment by pratik227** [comment]
Hi @fandegoldo 

I will check this issue and let you know.

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
1. grouping don't work when you want to customize slots
2. header filter don't work when you want to customize slots


This will not work as I'm not emitting all data.

**filter with selected options don't work when you want to customize slots (for example, i have replaced value true/false by a checkbox)** - Regarding this I will try to add this in next release
