### ISSUE TITLE
QGrid Select All and DatePicker on Column Filtering 

### ISSUE THREAD

**Issue by AuliaAmirullah15** [pratik227/quasar-qgrid#18]
Is there a way to show the word "all" when the select box on column filtering is empty? And is there a date filter that shows datepicker plugin when the date column filtering is clicked?

**Comment by pratik227** [comment]
HI @AuliaAmirullah15,

Currently, There is no such date filter Available.

`Is there a way to show the word "all" when the select box on column filtering is empty` - Ok I will add this in next release

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Hi @AuliaAmirullah15,

Finally, I managed to add this feature will be available in the next release. I will let you know once it's published

**Comment by pratik227** [comment]
@AuliaAmirullah15  

It's published now. You can refer to the documentation.

https://next-quasar-qgrid.netlify.app/example-qgrid-date-range

# Support

If this helped you in any way, you can contribute to the package's long term survival by supporting me:

### [💜 Support my open-source work on GitHub](https://github.com/sponsors/pratik227)

Be sure to check out my sponsor page.
