### ISSUE TITLE
Quasar 2 compatibility

### ISSUE THREAD

**Issue by Kirad20** [pratik227/quasar-qgrid#19]
I was installled qgrid in quasar 2 and used normally, the result is:
Failed to resolve component: q-grid at <BuscarExpediente onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >

**Comment by pratik227** [comment]
HI @Kirad20,

Just working on the documentation of the vue 3 version.

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Just Released the first version. Try 1.0.0-alpha.1 version.

https://next-quasar-qgrid.netlify.app/
