### ISSUE TITLE
Add more components to the repo

### ISSUE THREAD

**Issue by abidhkm** [pratik227/quasar-qgrid#20]
Hi is it possible to add more components to the repo? I tried adding one more component in this path _/ui/src/components/_ and tried to use that inside _dev/src/pages_ , but the newly created component is not rendered and getting this warning on console.
``` runtime-core.esm-bundler.js?9e79:38 [Vue warn]: Failed to resolve component: q-test 
  at <Test1 onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > > 
  at <RouterView> 
  at <QPageContainer> 
  at <QLayout view="lHh Lpr lFf" > 
  at <MyLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>

**Comment by pratik227** [comment]
Hi @abidhkm,

You need to register that component then you can use it.

Refer this file(https://github.com/pratik227/quasar-qgrid/blob/next/ui/src/vue-plugin.js)
