### ISSUE TITLE
Is there a way to save the order number to database?

### ISSUE THREAD

**Issue by chankl78** [pratik227/quasar-qgrid#21]
Can I check how to I save the new arranged items order into database?

Thanks.

**Comment by pratik227** [comment]
Hi @chankl78,

I think you can check the updated data and then compare it and then store the data in database

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Hi @chankl78 ,

I'm emitting a dragged_row event that you can use.

Demo - https://next-quasar-qgrid.netlify.app/example-qgrid-draggable-columns

Thanks,
Pratik Patel

**Comment by chankl78** [comment]
Great.  Thanks so much!

Will give a try on this.

Smile
Chan Kuan Leang
