### ISSUE TITLE
Quasar old version 

### ISSUE THREAD

**Issue by yavuzseker** [pratik227/quasar-qgrid#25]
Hello.
I got this error when try to install extension 
```
 "Extension(qgrid): is not compatible with quasar v1
.12.3. Required version: ^2.0.0-beta.12"
```
I dont want upgrade my Quasar version.so How can i use this extension for Q  v1?

**Comment by pratik227** [comment]
Try to install 0.0.8 version.

`npm i quasar-app-extension-qgrid@0.0.8 `

**Comment by yavuzseker** [comment]
Thanks for reply.I tried it but Error changed . 
New error
`Vue warn]: Unknown custom element: <q-grid> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
My qgrid element :
```
  <q-grid 
        ref="table"  
        v-if="isLoading==true && type=='ham'" 
        :data="tableData" :columns="columns" 
        :visible_columns="visibleColumns" 
        row-key="name"
        :columns_filter="true" 
        dense :fullscreen="true" 
         :global_search="true"  
         :selected="selectedRow"  
        selection="multiple" 
        file_name="sample" 
        @selected-val="getSelected($event)">
    </q-grid>
```
P.s.It was working before

**Comment by pratik227** [comment]
Try 

`quasar ext add qgrid@0.0.8`

**Comment by yavuzseker** [comment]
oh thx bro.Its working now.:)

**Comment by pratik227** [comment]
Great.

Closing this issue @yavuzseker
