### ISSUE TITLE
Slots available

### ISSUE THREAD

**Issue by AndreMPCosta** [pratik227/quasar-qgrid#40]
Which slots are available from q-table?

I'm trying to use for instance v-slot:header and it's not working. The only one that seems to be working is the body slot.

**Comment by pratik227** [comment]
Hi @AndreMPCosta,

For now it only supports body slot.

Give me some time I will try and add header slot 

Thanks,
Pratik Patel

**Comment by AndreMPCosta** [comment]
@pratik227 
Thanks, it would be great :)

**Comment by pratik227** [comment]
Hi @AndreMPCosta ,

Added new header slot in the new version. You can check.

https://next-quasar-qgrid.netlify.app/example-qgrid-header-slot-demo

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Closing this issue @AndreMPCosta

**Comment by AndreMPCosta** [comment]
Thanks, but I was in a hurry and ended up using q-table and implementing the filtering myself on the v-slot:header.

**Comment by pratik227** [comment]
:weary:
