### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by Nova38** [pratik227/quasar-qgrid#45]
I have had issues adding this app extension to my quasar projects. I have tried following both the app extension method and adding to my boot order. When I add it to a brand new project I am prompted to install @quasar/app, but after i install the missing package quasar is no longer able to recognize that it is a valid Quasar project.  I was able to get the demo project to run, but cant get it to work properly. I have test this on several computers  running node 14 and node 16

Here is the output from the installation process 
```
√ What would you like to build? » App with Quasar CLI, let's go!
√ Project folder: ... quasar-project
√ Pick Quasar version: » Quasar v2 (Vue 3 | latest and greatest)
√ Pick script type: » Typescript
√ Pick Quasar App CLI variant: » Quasar App CLI with Vite (BETA stage)
√ Package name: ... quasar-project
√ Project product name: (must start with letter if building mobile apps) ... Quasar App
√ Project description: ... A Quasar Project
√ Author: ... Thomas <dev.csnova@gmail.com>
√ Pick a Vue component style: » Composition API
√ Pick your CSS preprocessor: » Sass with SCSS syntax
√ Check the features needed for your project: » ESLint
√ Pick an ESLint preset: » Prettier

 Quasar • Generating files...

 - index.html
 - postcss.config.js
 - quasar.config.js
 - README.md
 - .editorconfig
 - .gitignore
 - package.json
 - tsconfig.json
 - public/favicon.ico
 - src/App.vue
 - src/env.d.ts
 - src/quasar.d.ts
 - src/shims-vue.d.ts
 - .vscode/extensions.json
 - .vscode/settings.json
 - public/icons/favicon-128x128.png
 - public/icons/favicon-16x16.png
 - public/icons/favicon-32x32.png
 - public/icons/favicon-96x96.png
 - src/assets/quasar-logo-vertical.svg
 - src/boot/.gitkeep
 - src/components/EssentialLink.vue
 - src/components/ExampleComponent.vue
 - src/components/models.ts
 - src/layouts/MainLayout.vue
 - src/pages/ErrorNotFound.vue
 - src/pages/IndexPage.vue
 - src/router/index.ts
 - src/router/routes.ts
 - src/css/app.scss
 - src/css/quasar.variables.scss
 - .eslintignore
 - .eslintrc.js
 - .prettierrc

 Quasar •  SUCCESS  • The project has been scaffolded
```

```
 App • Running "qgrid" Quasar App Extension...

 App • ⚠️  Extension(qgrid): Dependency not found - @quasar/app. Please install it.
```

```
❯ npm i @quasar/app

added 520 packages, and audited 921 packages in 25s

136 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 high, 2 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

```
❯ quasar dev

 App • ⚠️  Error. This command must be executed inside a Quasar v1+ project folder.

```

**Comment by pratik227** [comment]
Hi @Nova38,

For Quasar v1+  You need to use 0.0.8 QGrid version. The latest version is supporting Quasar V2

quasar ext add qgrid@0.0.8

Try this and let me know if it works. Or if you can create sample repo that will be great

Thanks,
Pratik Patel

**Comment by Nova38** [comment]
I will create a sample repo later today, but I am using quazar v2 I believe. ( I am using vue3 and vite which aren't options for v1 to me knowledge) It only gives me the v1 error after I try and install the quazar/app after it tells me to when I try to launch the dev server after installing the extension.

**Comment by pratik227** [comment]
Ok I will check I think the issue is with vite. I'm not familiar with that but will check 

Thanks,
Pratik Patel

**Comment by Nova38** [comment]
I went the install process and selected webpack and it appears that it successfully installed the app component. So i think you are correct that the issue appears to be linked to vite.

**Comment by pratik227** [comment]
Yes I need to check what exactly I need to change for vite

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Hi @Nova38,

Can you try the latest version in the vite app? Let me know if it works.

Thanks,
Pratik Patel

**Comment by Nova38** [comment]
That did it. It is now working. Thank you!!

**Comment by pratik227** [comment]
> That did it. It is now working. Thank you!!

🥳🥳🚀🚀
