### ISSUE TITLE
vue-cli

### ISSUE THREAD

**Issue by muzammil17** [pratik227/quasar-qgrid#6]
Hey im working on vue cli and added quasar in my project so is there any way to use quasar extension with vue cli ?

**Comment by pratik227** [comment]
I don't think You can use that directly. But you can copy paste the QGrid Component code that uses that component and it will work.

**Comment by muzammil17** [comment]
Is it possible for you to provide the code of qgrid table having search filter on each column ?

**Comment by pratik227** [comment]
It's there in the documentation. see the example for Column Filter. ` <q-grid :data="data" :columns="columns" :columns_filter="true"></q-grid>`

**Comment by muzammil17** [comment]
Its not possible to download qgrid extension in vue cli

**Comment by pratik227** [comment]
But you can copy that component code in your project and you can use that component. - https://github.com/pratik227/quasar-qgrid/blob/master/app-extension/src/components/QGrid.vue

**Comment by pratik227** [comment]
Codepen - https://codepen.io/Pratik__007/pen/zYqegKK

In Codepen - I have changed just 1 code 

`this.uuid = '501e7ae1-7e6f-b923-3e84-4e946bff31a8';`

You can use that quasar uid() function 

```
import { uid } from 'quasar'

let uid = uid()
```

You can refer the codepen code.
