### ISSUE TITLE
Component not working in Vite

### ISSUE THREAD

**Issue by tombed154** [pratik227/quasar-qgrid#63]
Hi, im trying to use component in Vite by using:
`import { Component as QGrid } from 'quasar-ui-qgrid'`

but im getting console error 
`The requested module '/node_modules/.vite/deps/quasar-ui-qgrid.js?t=1659087973036&v=7c418584' does not provide an export named 'Component'`

If i try to import like:
`import QGrid from 'quasar-ui-qgrid'`

Im getting console error
`Cannot set properties of undefined (setting 'moment')`

Any suggestions how to get this to work?

**Comment by pratik227** [comment]
`import QGrid from 'quasar-ui-qgrid/src/components/QGrid.vue'
`

Try this

**Comment by tombed154** [comment]
Thank you, this solved my problem
