### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by fjbardelli** [pratik227/quasar-qgrid#64]
Hello, this is a great job. It is possible, just as the example of the filter by date range is done, it makes a filter by a numerical field bounded between two values.

Thank you

**Comment by pratik227** [comment]
Ok. I will check

**Comment by fjbardelli** [comment]
Thank you

**Comment by pratik227** [comment]
Hi @fjbardelli 

Added number range filter

Demo - https://next-quasar-qgrid.netlify.app/example-qgrid-number-range

Example -
```
{
    name: 'sodium', label: 'Sodium (mg)', field: 'sodium',
    filter_type: 'number_range'
  },

```

If this helped you in any way, you can contribute to the package's long term survival by supporting me:

### [💜 Support my open-source work on GitHub](https://github.com/sponsors/pratik227)

Be sure to check out my sponsor page.

**Comment by fjbardelli** [comment]
Hi
Hugely grateful. A tremendous functionality has remained. and it is very useful for me, I am in a migration project and this greatly enhances the grid. And I find it unbelievable.

Thank you very much

**Comment by pratik227** [comment]
Closing this issue
