### ISSUE TITLE
Pagination doesn't work properly

### ISSUE THREAD

**Issue by danimog** [pratik227/quasar-qgrid#65]
How can I set a different rowsPerPage in pagination?
If I set a variable
mypagination: {
       rowsPerPage : 10
}

I see 10 rows per page but pagination doesn't work anymore (I can't switch to second, third, ecc... pages)

**Comment by rafaelameilda** [comment]
see if it helps you


(https://dragged-column-pagination.netlify.app/#/)

(https://github.com/rafaelameilda/new-q-grid-pagination/blob/master/src/pages/Index.vue)

**Comment by pratik227** [comment]
@danimog  did @rafaelameilda solution works ?

**Comment by danimog** [comment]
> @danimog did @rafaelameilda solution works ?
yes, it works! thanks

**Comment by pratik227** [comment]
Closing this issue
