### ISSUE TITLE
Selected array on multi selection not working

### ISSUE THREAD

**Issue by Yogiii** [pratik227/quasar-qgrid#73]
Hello, 

First, thanks for your work,
Im testing the component with multi selection and it seems the selected array is not working. It is always empty
Here the simple exemple i use : selected ref is always empty

```
<template>
  <q-grid :data="data" :columns="columns" :columns_filter="true" :draggable="true" selection="multiple"
          :csv_download="true" file_name="sample" :groupby_filter="true"
          :selected="selected"
          @selected-val="GetSelected($event)"></q-grid>

  <div class="q-mt-md">
    Selected: {{ JSON.stringify(selected) }}
  </div>


</template>

**....**

export default defineComponent({
  name: "GroupingComponent",
  setup() {
    return {
      columns,
      data,
      selected:ref([]),
      GetSelected(Selected) {
        console.log(Selected)
        console.log(this.selected)
      }
    }
  }
})
</script>
```

**Comment by pratik227** [comment]
Yes it will not update that variable.

You need to reassign it to selected.

```
<q-grid :data="data" :columns="columns" :columns_filter="true" :draggable="true" selection="multiple"
            :csv_download="true" file_name="sample" :groupby_filter="true"
            :selected="selected"
            @selected-val="GetSelected($event)">
      <template v-slot:header="props">
        <q-tr :props="props">
          <q-th auto-width></q-th>
          <q-th
            v-for="col in props.cols"
            class="text-italic text-purple"
          >
            {{ col.label }}
          </q-th>
        </q-tr>
      </template>
    </q-grid>
    {{selected}}
```

```
setup() {
    return {
      data,
      columns,
      selected: ref([]),
      GetSelected(Selected) {
        this.selected = Selected
        console.log(Selected)
        console.log(this.selected)
      }
    }
  }
```

This work fine for me. let me know if it works

**Comment by Yogiii** [comment]
Perfect thank you !

**Comment by Yogiii** [comment]
Im trying to add a button to clear the selection, 
I tried to clear the ref seleted array, is not working
Could you help me please

**Comment by pratik227** [comment]
Please Try the new version.

```
<q-btn @click="selected=[]" label="Clear Selection"></q-btn>

    <q-grid :data="data" :columns="columns" :columns_filter="true" :draggable="true" selection="multiple"
            :csv_download="true" file_name="sample" :groupby_filter="true"
            :selected="selected"
            @selected-val="GetSelected($event)">
      <template v-slot:header="props">
        <q-tr :props="props">
          <q-th auto-width></q-th>
          <q-th
            v-for="col in props.cols"
            class="text-italic text-purple"
          >
            {{ col.label }}
          </q-th>
        </q-tr>
      </template>
    </q-grid>
```

**Comment by Yogiii** [comment]
Hello,
Its cleaning the selected ref, but the checkboxs are still checked

**Comment by pratik227** [comment]
It's working fine for me

**Comment by pratik227** [comment]
[screencast-localhost_8080-2022.09.30-18_07_11.webm](https://user-images.githubusercontent.com/34883558/193271377-a1c82a34-5976-4e53-9467-96ecdf607d05.webm)

```<q-page padding>
    <q-btn @click="selected=[]" label="Clear Selection"></q-btn>

    <q-grid :data="data" :columns="columns" :columns_filter="true" :draggable="true" selection="multiple"
            :csv_download="true" file_name="sample" :groupby_filter="true"
            :selected="selected"
            @selected-val="GetSelected($event)">
      <template v-slot:header="props">
        <q-tr :props="props">
          <q-th auto-width></q-th>
          <q-th
            v-for="col in props.cols"
            class="text-italic text-purple"
          >
            {{ col.label }}
          </q-th>
        </q-tr>
      </template>
    </q-grid>
    {{selected}}
  </q-page>```
  
  
export default defineComponent({
  name: 'Test10',
  setup() {
    return {
      data,
      columns,
      selected: ref([]),
      GetSelected(Selected) {
        this.selected = Selected
        console.log(Selected)
        console.log(this.selected)
      }
    }
  }
})

**Comment by pratik227** [comment]
Please check you are using the latest version or not.

**Comment by Yogiii** [comment]
Just reinstalled now, the latest version i found is 1.0.9, and still not working


![image](https://user-images.githubusercontent.com/11574668/193430147-1ab93846-5792-4910-b1e8-65f253589780.png)

**Comment by pratik227** [comment]
Please refer this Repo it's working 

https://github.com/pratik227/grid-check

**Comment by plebanip** [comment]
Hi,

related to the same topic, I have the opposite problem. When I select a single row (regardless of the row), the components select all the rows. 

Any hints?

Here the code. Thanks!

```<template>
  <q-page class="q-pa-md">
    <q-grid
      :data="my_data"
      :columns="my_columns"
      :columns_filter="true"
      selection="multiple"
      :selected="selected"
      @selected-val="GetSelected($event)"
    ></q-grid>
    <q-card>
      <q-card-section> Selected: {{ selected }} </q-card-section>
    </q-card>
  </q-page>
</template>

<script>
import { defineComponent, ref } from "vue";

import DataService from "../services/DataService";

const my_columns = [
  {
    name: "id",
    required: true,
    sortable: true,
    align: "left",
    field: "id",
  },
  {
    name: "name",
    required: true,
    sortable: true,
    align: "left",
    field: "name",
  },
  {
    name: "address",
    required: true,
    sortable: true,
    align: "left",
    field: "address",
  },
  {
    name: "zip",
    required: true,
    sortable: true,
    align: "left",
    field: "zip",
  },
  {
    name: "city",
    required: true,
    sortable: true,
    align: "left",
    field: "city",
  },
];

export default defineComponent({
  name: "NamePage",

  setup() {
    return {
      my_data: ref([]),
      my_columns,
      selected: ref([]),
      GetSelected(Selected) {
        this.selected = Selected;
      },
    };
  },
  created() {
    this.DataService = new DataService();
  },
  mounted() {
    this.DataService.getData().then((data) => (this.my_data = data));
  },
});
</script>```

**Comment by pratik227** [comment]
@plebanip You need to provide `:row-key=""` which will be unique per data. By default it's `name`.

> Property of each row that defines the unique key of each row (the result must be a primitive, not Object, Array, etc);

**Comment by Yogiii** [comment]
Hello, 

I tried following ;
- reinstall the component with : `quasar ext add qgrid` -> not working
- Delete node_modules folder, and reinstall all dependencies -> not working

- I clone your qgrid-check project, and copy manually your QGrid.vue component on mine -> **Worked**

Did you publish your last version ?

**Comment by pratik227** [comment]
I have created that repo after publishing the package only So I think it will work. Maybe it's installing using cache try to clear npm cache and then try to install it it should work.

**Comment by pratik227** [comment]
https://www.npmjs.com/package/quasar-ui-qgrid/v/1.0.16

**Comment by plebanip** [comment]
> @plebanip You need to provide `:row-key=""` which will be unique per data. By default it's `name`.
> 
> > Property of each row that defines the unique key of each row (the result must be a primitive, not Object, Array, etc);

thanks for the reply. Unfortunately, it does not work. I put

``:row-key="id"`` but when rendering I got a warning 
``
runtime-core.esm-bundler.js:38 [Vue warn]: Property "id" was accessed during render but is not defined on instance. 
``

Actually, id is one of the fields in the column 

Best

P.S.: I checked the documentation, but I was not able to find any mention to the row-key properties. Where is it?

**Comment by pratik227** [comment]
> > @plebanip You need to provide `:row-key=""` which will be unique per data. By default it's `name`.
> > > Property of each row that defines the unique key of each row (the result must be a primitive, not Object, Array, etc);
> 
> thanks for the reply. Unfortunately, it does not work. I put
> 
> `:row-key="id"` but when rendering I got a warning `runtime-core.esm-bundler.js:38 [Vue warn]: Property "id" was accessed during render but is not defined on instance. `
> 
> Actually, id is one of the fields in the column
> 
> Best
> 
> P.S.: I checked the documentation, but I was not able to find any mention to the row-key properties. Where is it?


@plebanip  It should be :row-key="'id'"

**Comment by pratik227** [comment]
Closing this issue.

**Comment by plebanip** [comment]
Hi Pratik,

sorry for re-opening the issue. I tried to use the ``:row-key="'_id'"`` as you suggested but the behavior remains the same. When I click on just one of the items, all the items will become selected. To have a confirmation, I printed out the ``selected`` variable and I confirm that the values of the  ``_id`` property is unique for each item

Thanks

**Comment by pratik227** [comment]
Example - https://github.com/pratik227/grid-check/blob/main/src/pages/IndexPage.vue

Sorry my bad :row_key

:row_key="'_id'"

**Comment by Yogiii** [comment]
Hello Pratik,

Im trying to customize only one particular column with body slot, 
but with this i need to redefine others columns also, including checkbox on the first columns with his behaviour that is problematic.
How can i do ?

![image](https://user-images.githubusercontent.com/11574668/195392505-9aa50ce1-62ae-457b-8a91-5527d103e70c.png)


Thank you

**Comment by plebanip** [comment]
> Example - https://github.com/pratik227/grid-check/blob/main/src/pages/IndexPage.vue
> 
> Sorry my bad :row_key
> 
> :row_key="'_id'"

Great! it works! Thanks a lot
