### ISSUE TITLE
Customize column

### ISSUE THREAD

**Issue by Yogiii** [pratik227/quasar-qgrid#75]
Hello Pratik,

Im trying to customize only one particular column with body slot,
but with this i need to redefine others columns also, including checkbox on the first columns with his behaviour that is problematic.
How can i do ?

![image](https://user-images.githubusercontent.com/11574668/195844456-276a44ec-edb2-4699-9df1-74592c01bb3c.png)

**Comment by pratik227** [comment]
Yes You need to add other  columns as well there is no such a option for you to cutomize signle column
