### ISSUE TITLE
Date range filter

### ISSUE THREAD

**Issue by haizad** [pratik227/quasar-qgrid#8]
Hi Pratik, thank you so much for this extension.

Do you have provide a function for date range filter? I don't find any date range filters on your demos, but I will try to create one.

Thanks again.

**Comment by pratik227** [comment]
Hi @haizad,

Thanks, I have not built the date range filter yet. But will add in the feature if it works in my component.

**Comment by pratik227** [comment]
Hi @haizad,

Closing this issue for now.
