### ISSUE TITLE
Filter data

### ISSUE THREAD

**Issue by danimog** [pratik227/quasar-qgrid#85]
Hi!
with more than a thousand items, filter in q-grid table doesn't work properly.
It shows first item correct but then add in the list other items (that are not correct)..
It's a known issue?

Thanks!!

**Comment by pratik227** [comment]
I don't think it's going to create any issue for lots of records.

Can you create sample repo for the same ?

**Comment by pratik227** [comment]
Github - https://github.com/rafaelameilda/new-q-grid-pagination/blob/master/src/pages/Index.vue

Demo - https://dragged-column-pagination.netlify.app/#/

**Comment by pratik227** [comment]
Closing the issue because of inactive
