### ISSUE TITLE
How to get filtered data when the column filtered

### ISSUE THREAD

**Issue by murataras** [pratik227/quasar-qgrid#90]
Required to display subtotals when filtering

**Comment by kurtisas-k** [comment]
Short-term solution for me was to throw a ref in the table and call this.$refs.tableId.rows and then throw a deep watch on the data object in the :rows prop. I didn't need it for calculation but for synchronizing data to an external DB, as well as exporting the winnowed data to the CSV as opposed to the full data set.

**Comment by pratik227** [comment]
Hi @kurtisas-k @murataras,

New emit event is added for getting filtered data.

**FilteredData**

**Description**
For getting filtered data

**Example**

@FilteredData="filteredData($event)"

https://next-quasar-qgrid.netlify.app/

Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Closing this issue.
