### ISSUE TITLE
Returns an undefined column error when using a functional field in column definitions

### ISSUE THREAD

**Issue by murataras** [pratik227/quasar-qgrid#91]
```
const columns = [
  {
    name: "evrakTip",
    align: "center",
    label: "Evrak Tipi",
    field: (row) => row.DocTypes.TypeCode,
    sortable: true,
    filter_type: "select",
    show_filter: true,
  },
  ...
];
```
I used functional field

>  field: (row) => row.DocTypes.TypeCode 

return this error in getColumnOptions method

![resim](https://user-images.githubusercontent.com/34946402/219952157-cfe7aa80-0b41-4ed2-bf18-4877fc0c0deb.png)

**Comment by pratik227** [comment]
Hi,

QGrid doesn't support function field

**Comment by murataras** [comment]
OK thanks

**Comment by pratik227** [comment]
Closing this issue
