### ISSUE TITLE
cannot sort when pass prop pagination as an object

### ISSUE THREAD

**Issue by bomb-kst** [pratik227/quasar-qgrid#93]
` <q-grid :data="data" :columns="columns" :columns_filter="true" :pagination="{ rowsPerPage: data.length }"></q-grid>`

**Comment by pratik227** [comment]
Hi @bomb-kst,

Fix in the latest version. Please check.

**Please note that If you are using ServerSide Pagination then you need to pass ssr_pagination props as true.**


Thanks,
Pratik Patel

**Comment by pratik227** [comment]
Closing this issue.
